// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: logic/bible/schema.proto

package bible

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Verse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookAbbr      string                 `protobuf:"bytes,1,opt,name=book_abbr,json=bookAbbr,proto3" json:"book_abbr,omitempty"`
	Chapter       int32                  `protobuf:"varint,2,opt,name=chapter,proto3" json:"chapter,omitempty"`
	Verse         int32                  `protobuf:"varint,3,opt,name=verse,proto3" json:"verse,omitempty"`
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Verse) Reset() {
	*x = Verse{}
	mi := &file_logic_bible_schema_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Verse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Verse) ProtoMessage() {}

func (x *Verse) ProtoReflect() protoreflect.Message {
	mi := &file_logic_bible_schema_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Verse.ProtoReflect.Descriptor instead.
func (*Verse) Descriptor() ([]byte, []int) {
	return file_logic_bible_schema_proto_rawDescGZIP(), []int{0}
}

func (x *Verse) GetBookAbbr() string {
	if x != nil {
		return x.BookAbbr
	}
	return ""
}

func (x *Verse) GetChapter() int32 {
	if x != nil {
		return x.Chapter
	}
	return 0
}

func (x *Verse) GetVerse() int32 {
	if x != nil {
		return x.Verse
	}
	return 0
}

func (x *Verse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type Book struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Abbreviation  string                 `protobuf:"bytes,2,opt,name=abbreviation,proto3" json:"abbreviation,omitempty"`
	Chapters      []*Chapter             `protobuf:"bytes,3,rep,name=chapters,proto3" json:"chapters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Book) Reset() {
	*x = Book{}
	mi := &file_logic_bible_schema_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Book) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Book) ProtoMessage() {}

func (x *Book) ProtoReflect() protoreflect.Message {
	mi := &file_logic_bible_schema_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Book.ProtoReflect.Descriptor instead.
func (*Book) Descriptor() ([]byte, []int) {
	return file_logic_bible_schema_proto_rawDescGZIP(), []int{1}
}

func (x *Book) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Book) GetAbbreviation() string {
	if x != nil {
		return x.Abbreviation
	}
	return ""
}

func (x *Book) GetChapters() []*Chapter {
	if x != nil {
		return x.Chapters
	}
	return nil
}

type Chapter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Verses        []string               `protobuf:"bytes,1,rep,name=verses,proto3" json:"verses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chapter) Reset() {
	*x = Chapter{}
	mi := &file_logic_bible_schema_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chapter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chapter) ProtoMessage() {}

func (x *Chapter) ProtoReflect() protoreflect.Message {
	mi := &file_logic_bible_schema_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chapter.ProtoReflect.Descriptor instead.
func (*Chapter) Descriptor() ([]byte, []int) {
	return file_logic_bible_schema_proto_rawDescGZIP(), []int{2}
}

func (x *Chapter) GetVerses() []string {
	if x != nil {
		return x.Verses
	}
	return nil
}

type BibleData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Books         []*Book                `protobuf:"bytes,1,rep,name=books,proto3" json:"books,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BibleData) Reset() {
	*x = BibleData{}
	mi := &file_logic_bible_schema_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BibleData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BibleData) ProtoMessage() {}

func (x *BibleData) ProtoReflect() protoreflect.Message {
	mi := &file_logic_bible_schema_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BibleData.ProtoReflect.Descriptor instead.
func (*BibleData) Descriptor() ([]byte, []int) {
	return file_logic_bible_schema_proto_rawDescGZIP(), []int{3}
}

func (x *BibleData) GetBooks() []*Book {
	if x != nil {
		return x.Books
	}
	return nil
}

var File_logic_bible_schema_proto protoreflect.FileDescriptor

const file_logic_bible_schema_proto_rawDesc = "" +
	"\n" +
	"\x18logic/bible/schema.proto\"h\n" +
	"\x05Verse\x12\x1b\n" +
	"\tbook_abbr\x18\x01 \x01(\tR\bbookAbbr\x12\x18\n" +
	"\achapter\x18\x02 \x01(\x05R\achapter\x12\x14\n" +
	"\x05verse\x18\x03 \x01(\x05R\x05verse\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\"d\n" +
	"\x04Book\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\"\n" +
	"\fabbreviation\x18\x02 \x01(\tR\fabbreviation\x12$\n" +
	"\bchapters\x18\x03 \x03(\v2\b.ChapterR\bchapters\"!\n" +
	"\aChapter\x12\x16\n" +
	"\x06verses\x18\x01 \x03(\tR\x06verses\"(\n" +
	"\tBibleData\x12\x1b\n" +
	"\x05books\x18\x01 \x03(\v2\x05.BookR\x05booksB\rZ\vlogin/bibleb\x06proto3"

var (
	file_logic_bible_schema_proto_rawDescOnce sync.Once
	file_logic_bible_schema_proto_rawDescData []byte
)

func file_logic_bible_schema_proto_rawDescGZIP() []byte {
	file_logic_bible_schema_proto_rawDescOnce.Do(func() {
		file_logic_bible_schema_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_logic_bible_schema_proto_rawDesc), len(file_logic_bible_schema_proto_rawDesc)))
	})
	return file_logic_bible_schema_proto_rawDescData
}

var file_logic_bible_schema_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_logic_bible_schema_proto_goTypes = []any{
	(*Verse)(nil),     // 0: Verse
	(*Book)(nil),      // 1: Book
	(*Chapter)(nil),   // 2: Chapter
	(*BibleData)(nil), // 3: BibleData
}
var file_logic_bible_schema_proto_depIdxs = []int32{
	2, // 0: Book.chapters:type_name -> Chapter
	1, // 1: BibleData.books:type_name -> Book
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_logic_bible_schema_proto_init() }
func file_logic_bible_schema_proto_init() {
	if File_logic_bible_schema_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_logic_bible_schema_proto_rawDesc), len(file_logic_bible_schema_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_logic_bible_schema_proto_goTypes,
		DependencyIndexes: file_logic_bible_schema_proto_depIdxs,
		MessageInfos:      file_logic_bible_schema_proto_msgTypes,
	}.Build()
	File_logic_bible_schema_proto = out.File
	file_logic_bible_schema_proto_goTypes = nil
	file_logic_bible_schema_proto_depIdxs = nil
}
